DECLARE SUB BACK(I AS INTEGER,J AS INTEGER)
DECLARE FUNCTION PRIME(X AS INTEGER)AS INTEGER
DIM SHARED AS INTEGER N
INPUT "N=";N
DIM SHARED AS INTEGER S,T,A(N,N)
FOR C=1 TO (N+1)\2
    FOR I=C TO N+1-C
        FOR J=C TO N+1-C
            A(I,J)=C
        NEXT
    NEXT
NEXT
I=1:J=1:S=A(1,1)
BACK(I,J)
PRINT "S=";T
SLEEP
END

FUNCTION PRIME(X AS INTEGER)AS INTEGER
    PRIME=-1
    FOR C=2 TO INT(SQR(X))
        IF X MOD C=0 THEN PRIME=0
    NEXT
    IF X<2 THEN PRIME=0
END FUNCTION

SUB BACK(I AS INTEGER,J AS INTEGER)
    IF I=N AND J=N AND PRIME(S) THEN T=T+1
    I=I+1
    IF I<=N THEN S=S+A(I,J):BACK(I,J):S=S-A(I,J)
    I=I-1
    J=J+1
    IF J<=N THEN S=S+A(I,J):BACK(I,J):S=S-A(I,J)
    J=J-1
END SUB 