DIM AS STRING N,M
INPUT N
INPUT M
DIM AS INTEGER A(128),B(128),C(128),LN,LM,I,J,F,S
LN=LEN(N)
LM=LEN(M)
IF LN<>LM THEN PRINT "ERROR":SLEEP:END
FOR I=1 TO LN
    A(ASC(MID(N,I,1)))=A(ASC(MID(N,I,1)))+1
NEXT I
FOR I=1 TO LM
    B(ASC(MID(M,I,1)))=B(ASC(MID(M,I,1)))+1
NEXT I
FOR I=1 TO 127
    FOR J=I+1 TO 128
        IF A(J)>A(I) THEN SWAP A(I),A(J)
    NEXT J
NEXT I  
FOR I=1 TO 127
    FOR J=I+1 TO 128
        IF B(J)>B(I) THEN SWAP B(I),B(J)
    NEXT J
NEXT I
F=-1
FOR I=1 TO 128
    IF A(I)<>B(I) THEN F=0:EXIT FOR
NEXT I
IF F=0 THEN PRINT "ERROR":SLEEP:END
FOR I=1 TO 128
    C(A(I))=C(A(I))+1
NEXT I
S=1
FOR I=1 TO 128
    IF C(I)>1 THEN
        FOR J=1 TO C(I)
            S=S*J
        NEXT J
    END IF
NEXT I
PRINT S
SLEEP
END

