DIM AS STRING N
INPUT "N=";N
DIM AS INTEGER LN,I,K,J,P,Q
LN=LEN(N)
DIM AS INTEGER A(LN)
FOR I=1 TO LN
    A(I)=VAL(MID(N,I,1))
NEXT I
K=LN
DO WHILE A(K-1)>=A(K):K=K-1:LOOP
J=LN
DO WHILE A(K-1)>=A(J):J=J-1:LOOP
SWAP A(K-1),A(J)
FOR P=K TO LN-1
    FOR Q=P+1 TO LN
        IF A(P)>A(Q) THEN SWAP A(P),A(Q)
    NEXT Q
NEXT P
FOR I=1 TO LN:PRINT USING "#";A(I);:NEXT I:PRINT ,


FOR I=1 TO LN
    A(I)=VAL(MID(N,I,1))
NEXT I
K=LN
DO WHILE A(K-1)<=A(K):K=K-1:LOOP
J=LN
DO WHILE A(K-1)<=A(J):J=J-1:LOOP
SWAP A(K-1),A(J)
FOR P=K TO LN-1
    FOR Q=P+1 TO LN
        IF A(P)<A(Q) THEN SWAP A(P),A(Q)
    NEXT Q
NEXT P
FOR I=1 TO LN:PRINT USING "#";A(I);:NEXT I
SLEEP
