DECLARE SUB BACK(BYVAL I AS INTEGER,BYVAL S AS INTEGER)
DIM AS STRING FN
INPUT FN
OPEN FN FOR INPUT AS #1
DIM SHARED AS INTEGER N,MAX
INPUT #1,N
DIM SHARED AS STRING A(N)
FOR I=1 TO N
    INPUT #1,A(I)
NEXT I
BACK(1,0)
PRINT MAX
SLEEP 

SUB BACK(BYVAL I AS INTEGER,BYVAL S AS INTEGER)
    S=S+1
    IF S>MAX THEN MAX=S
    FOR J=I+1 TO N
        IF MID(A(I),2,1)=MID(A(J),1,1) THEN 
            BACK(J,S)
        END IF
    NEXT J
END SUB
