DIM AS STRING P,Q,AA,BB
INPUT "P,Q=";P,Q
AA=P:BB=Q
DIM AS INTEGER LA,LB,F,I,K
LA=LEN(AA):LB=LEN(BB)
IF LA<LB OR LA=LB AND AA<BB THEN 
    SWAP LA,LB:SWAP AA,BB
    PRINT TAB(3+LA-LB);
    PRINT P
    PRINT "-)";Q
    F=-1
ELSE
    PRINT "  ";P
    PRINT "-)";
    PRINT TAB(3+LA-LB);Q
END IF
DIM AS INTEGER A(LA),B(LA)
FOR I=1 TO LA
    A(I)=VAL(MID(AA,LA+1-I,1))
NEXT I
FOR I=1 TO LB
    B(I)=VAL(MID(BB,LB+1-I,1))
NEXT I
FOR I=1 TO LA
    A(I)=A(I)-B(I)
    IF A(I)<0 THEN A(I+1)=A(I+1)-1:A(I)=A(I)+10
NEXT I
K=LA
DO WHILE A(K)=0 AND K>1 :K=K-1:LOOP
FOR I=1 TO LA+2:PRINT "-";:NEXT I
PRINT
FOR I=1 TO K
    LOCATE 5,(3+LA-I)
    PRINT USING "#";A(I);
NEXT I
IF F=-1 THEN
    LOCATE 5,2+LA-K
    PRINT "-";
END IF
SLEEP
