DIM AS STRING FN
INPUT FN
OPEN FN+".TXT" FOR INPUT AS #1
INPUT #1,N
DIM AS INTEGER A(N),F(N),I,J,MAX
FOR I=1 TO N
    INPUT #1,A(I)
NEXT I

A(0)=214783647
FOR I=1 TO N
    FOR J= 0 TO I-1
        IF  A(J)>A(I) AND F(J)+1>F(I)   THEN F(I)=F(J)+1
    NEXT J
NEXT I

MAX=F(1)
FOR I=2 TO N
    IF  F(I)>MAX THEN MAX=F(I)
NEXT I
PRINT MAX
CLOSE #1
SLEEP

    