DIM AS STRING FN
INPUT FN
OPEN FN FOR INPUT AS #1
INPUT #1,N
DIM AS INTEGER A(N),B(N)
FOR I=1 TO N
    INPUT #1,A(I)
    PRINT A(I);
NEXT I
PRINT

FOR I=1 TO N
    MAX=0
    FOR J=I-1 TO 1 STEP -1
        IF A(I)>A(J) AND B(J)>MAX THEN MAX=B(J)
    NEXT J
    B(I)=MAX+1
NEXT I

FOR I=1 TO N :PRINT B(I); :NEXT I:PRINT
MAX=0
FOR I=1 TO N
    IF B(I)>MAX THEN MAX=B(I)
NEXT I
PRINT MAX
SLEEP